version: '2'
services:
 jenkins:
  build: ./docker-in-jenkins
  ports:
   - "8080:8080"
   - "5000:5000"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /home/jbo/jenkins:/var/jenkins_home 
   - /usr/bin/docker:/usr/bin/docker 
  depends_on:
   - artifactory
 artifactory:
  image: docker.bintray.io/jfrog/artifactory-oss:latest
  ports:
   - "8081:8081"
